### ISSUE TITLE
Project Contain unnecessary files 

### ISSUE THREAD

**Issue by Gri-ffin** [Code-Done-Right/Sciencium#12]
I noticed in your project that you have a package-lock and yarn.lock files, which I think is redundant.

 I think you could stick with yarn since the file size is much smaller than package-lock and run yarn install to install dependencies, or if you prefer you could stick with npm and delete the package-lock and add it to .gitignore and let contributors run npm install since that will make cloning your project much more faster.

Or maybe you have an other opinion, I'm just saying my own.

**Comment by Code-Done-Right** [comment]
I'll think about it, thanks for pointing it out!
