### ISSUE TITLE
react-scripts not installing in firebase hosting job

### ISSUE THREAD

**Issue by Code-Done-Right** [Code-Done-Right/Sciencium#20]
![image](https://user-images.githubusercontent.com/81095108/152784320-59734d21-f9d2-48f1-a045-964495944eb9.png)

In here @harishbabu2007 , the `yarn.lock` has no dependency for installing `react-scripts`. I made a commit for this, please update the hosted project immediately.

**Comment by harishbabu2007** [comment]
i fixed the issue of the firebase-merge
