### ISSUE TITLE
Problem in dynamic background

### ISSUE THREAD

**Issue by Code-Done-Right** [Code-Done-Right/Sciencium#3]
In `Home.js`, the dynamic background seems to be behaving weirdly even thought the code and the CSS properties are all correct. This is a weird issue and I think it's some bug with the browser reading the code and properly applying the css properties to the screen, but I'm really not sure. Urgent help needed :(

this is when all 4 CSS properties are enabled:
![2022-01-31 (16)](https://user-images.githubusercontent.com/81095108/151796782-db3d923e-b5cd-446e-97e7-8c2b7b313cdd.png)

this is when `height` or `width` properties are removed/changed:
![2022-01-31 (17)](https://user-images.githubusercontent.com/81095108/151796861-98007755-8a9f-4658-a9c8-e7867d237bef.png)

this is when `position: relative;` is removed:
![2022-01-31 (18)](https://user-images.githubusercontent.com/81095108/151796912-81ee870e-5944-42b5-ac44-f9863788e282.png)

this is when `overflow: hidden;` is removed:
![2022-01-31 (19)](https://user-images.githubusercontent.com/81095108/151796978-cc9bc2cf-fa5e-49fa-b4bf-4422c7bd29ae.png)

Either way, all of the properties give erroneous backgrounds. I cannot seem to understand why it is breaking. Please help :((((

**Comment by PranjalRoy123** [comment]
Fixed in pr  #4
